
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloakdb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddlAuto: update