
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloakdb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddlAuto: update


keycloak:
  realm: spring-boot-keycloak #Realm name
  auth-server-url: http://localhost:8080/auth/
  resource: amol #client ID
  public-client: true
  bearer-only: true